### ISSUE TITLE
O Sistema considera a indicação da unidade de quem indicou e não do Indicado

### ISSUE THREAD

**Issue by WAGNERPFONSECA** [fernandotomasio/trainning#37]
O Sistema considera a indicação da unidade de quem indicou e não do Indicado, assim dará fora de vaga. Acertar para considerar a unidade do Indicado.

**Comment by fernandotomasio** [comment]
É importante considerar a OM de quem indicou, visto que haverá sempre o caso de organização do militar estar desatualizada ou mesmo de militar prestando serviço.

**Comment by WAGNERPFONSECA** [comment]
Não seria interessante considerar o OM Beneficiada? Pois seria fácil entender e abriria a possiblidade de corrigir falta de atualização SIGPES e prestação de serviço.
E também, é preciso corrigir o BUG que o cadastro de OM Beneficiada está pegando a unidade de quem indicou, não registra o cadastro feito em OM Beneficiada.
Na Guia Vagas, em distribuição de vagas, ele considera também quem indicou!

**Comment by fernandotomasio** [comment]
É importante manter a om que indicou, a fim de atender o caso em que o militar estiver prestando serviço, ou ainda quando o cadastro no SIGPES estiver desatualizado
