### ISSUE TITLE
EXCLUSÃO DE INDICAÇÕES - Não permite

### ISSUE THREAD

**Issue by WAGNERPFONSECA** [fernandotomasio/trainning#44]
Não está permitindo excluir indicações

**Comment by fernandotomasio** [comment]
Identificado o problema: não é possível excluir em cascata os pareceres associados, portanto quando tentamos excluir uma indicação que possua pareceres o camada de persistência dispara um erro

**Comment by fernandotomasio** [comment]
A solução é configurar o hibernate para excluir em cascata os pareceres associados a indicação a ser excluída

**Comment by fernandotomasio** [comment]
Resolvido
