### ISSUE TITLE
EXCLUSÃO DE MATRICULA - Não permite

### ISSUE THREAD

**Issue by WAGNERPFONSECA** [fernandotomasio/trainning#58]
Na Exclusão dos Matriculados na Turma
CIS045-2014OPR11 -6 SAGITARIO – AIDC - OPERACIONAL – ACC CINDACTA III 
Dá Excepction, não acha a Turma
![nao_exclui_matricula_1](https://cloud.githubusercontent.com/assets/8531745/14830126/66f81a6e-0bc5-11e6-8faa-538816975cb1.JPG)
![nao_exclui_matricula_1_2](https://cloud.githubusercontent.com/assets/8531745/14830127/66f82554-0bc5-11e6-9b33-1c128aeab3bb.JPG)

**Comment by fernandotomasio** [comment]
Resolvido
